class Const:

    STUDENTS_TABLE = "students"

    STUDENT_ID = "idstudents"
    STUDENT_FIRST_NAME = "first_name"
    STUDENT_LAST_NAME = "last_name"
    STUDENT_USER_NAME = "user_name"
    STUDENT_PASSWORD = "password"
    STUDENT_MATH = "math_grade"
    STUDENT_PROGRAMMING_LANGUAGE = "programming_langueges_grade"
    STUDENT_HUMAN_COMPUTER_INTERACTION = "human_computer_interaction_grade"
    STUDENT_GERMAN = "german_grade"
    STUDENT_ENGLISH = "english_grade"
    STUDENT_ALGORITHM = "algorithms_and_data_structure_grade"
    STUDENT_MATH_EXAM = "math_exam"
    STUDENT_PROGRAMMING_LANGUAGE_EXAM = "programming_langueges_exam"
    STUDENT_HUMAN_COMPUTER_INTERACTION_EXAM = "human_computer_interaction_exam"
    STUDENT_GERMAN_EXAM = "german_exam"
    STUDENT_ENGLISH_EXAM = "english_exam"
    STUDENT_ALGORITHM_EXAM = "algorithms_and_data_structure_exam"
    STUDENT_MATH_CREDITS = "math_credits"
    STUDENT_PROGRAMMING_LANGUAGE_CREDITS = "programming_langueges_credits"
    STUDENT_HUMAN_COMPUTER_INTERACTION_CREDITS = "human_computer_interaction_credits"
    STUDENT_GERMAN_CREDITS = "german_credits"
    STUDENT_ENGLISH_CREDITS = "english_credits"
    STUDENT_ALGORITHM_CREDITS = "algorithms_and_data_structure_credits"

    TEACHERS_TABLE = "teachers"
    TEACHER_ID = "idteacher"
    TEACHER_FIRST_NAME = "first_name"
    TEACHER_LAST_NAME = "last_name"
    TEACHER_USER_NAME = "user_name"
    TEACHER_PASSWORD = "password"
    TEACHER_SUBJECT = "subject"

    DIRECTOR_TABLE = "directors"
    DIRECTOR_ID = "iddirector"
    DIRECTOR_FIRST_NAME = "first_name"
    DIRECTOR_LAST_NAME = "last_name"
    DIRECTOR_USER_NAME = "user_name"
    DIRECTOR_PASSWORD = "password"

    SUBJECT_TABLE = "subjects"
    SUBJECT_ID = "idsubjects"
    SUBJECT_NAME = "name"

    HW_TABLE = "home_works"
    HW_MATH = "Math"
    HW_Programming_Langs = "Programming Langs"
    HW_Human_computer = "Human & computer"
    HW_German = "German"
    HW_English = "English"
    HW_Algorithms = "Algorithms"

    POINTS_TABLE = "points"
    POINTS_USER_NAME = "user_name"
    POINTS_MATH = "math_points"
    POINTS_PROGRAMMING_LANGUAGE = "programming_langueges_points"
    POINTS_HUMAN_COMPUTER_INTERACTION = "human_computer_interaction_points"
    POINTS_GERMAN = "german_points"
    POINTS_ENGLISH = "english_points"
    POINTS_ALGORITHM = "algorithms_and_data_structure_points"

